# Default values for openebs-monitoring-stack.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

## Provide a name in place of openebs-monitoring-stack for `app:` labels
##
nameOverride: ""

## Override the deployment namespace
##
namespaceOverride: ""

## Provide a k8s version to auto dashboard import script example: kubeTargetVersionOverride: 1.16.6
##
kubeTargetVersionOverride: ""

## Provide a name to substitute for the full names of resources
##
fullnameOverride: ""

## Labels to apply to all resources
##
commonLabels: {}
# scmhash: abc123
# myLabel: aakkmd

# Set dependencies chart values.yaml through parent values.yaml
# parent
#   |- child
#parent values.yaml can be passed to child but child values.yaml cannot be acced to parent
kube-prometheus-stack:
  grafana:
    enabled: true
  prometheus:
    ruleSelectorNilUsesHelmValues: false

grafana:
  enabled: true
  customDashboard: true
  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard

casType: "jiva"
